name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker Login
        env:
          DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file 14.0.Dockerfile --tag doodba:14.0-onbuild

      - name: Push docker image to docker hub
        run: |
          docker push saramadsoft/doodba:14.0-onbuild
